# Generated by Django 5.1.5 on 2025-03-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_language_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_hi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_hi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description_hi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_hi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="cancellation_policy_de",
            field=models.TextField(
                default="24 hours notice required for cancellation", null=True
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="cancellation_policy_en",
            field=models.TextField(
                default="24 hours notice required for cancellation", null=True
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="cancellation_policy_es",
            field=models.TextField(
                default="24 hours notice required for cancellation", null=True
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="cancellation_policy_fr",
            field=models.TextField(
                default="24 hours notice required for cancellation", null=True
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="cancellation_policy_hi",
            field=models.TextField(
                default="24 hours notice required for cancellation", null=True
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="certifications_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="certifications_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="certifications_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="certifications_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="certifications_hi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="name_hi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="description_hi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="name_hi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_de",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_en",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_es",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_fr",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_hi",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_de",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_en",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_es",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_fr",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_hi",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
    ]
