# Generated by Django 5.1.5 on 2025-03-29 07:22

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_shop_recurring_bookings_returns_coupons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shop_logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
    ]
